---
- name: Docker kong prepare
  hosts: all
  become: true

  tasks:
    - name: Ensure kong_log_dir exists
      file:
        state: directory
        path: "{{ kong_log_dir }}"
        group: "docker"
        mode: 0775

    - name: Check kong_postgres_data_dir exists
      stat:
        path: "{{ kong_postgres_data_dir }}"
      register: kong_postgres_data_dir_stat

    - name: Ensure kong_postgres_data_dir exists
      file:
        state: directory
        path: "{{ kong_postgres_data_dir }}"
        group: "docker"
        mode: 0775
      when: not kong_postgres_data_dir_stat.stat.exists

    - name: Ensure kong_postgres_log_dir exists
      file:
        state: directory
        path: "{{ kong_postgres_log_dir }}"
        group: "docker"
        mode: 0777

    - name: Ensure kong_dotenv_dir exists
      file:
        state: directory
        path: "{{ kong_dotenv_dir }}"
        mode: 0755

    - name: Touch .env
      file:
        path: "{{ kong_dotenv_dir }}/.env"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: Update .env
      lineinfile:
        path: "{{ kong_dotenv_dir }}/.env"
        regexp: "^{{ item.key }}="
        line: '{{ item.key }}={{ item.value }}'
      with_items:
        - key: "KONG_LOG_DIR"
          value: "{{ kong_log_dir }}"
        - key: "KONG_POSTGRES_PASSWORD"
          value: "{{ kong_postgres_password }}"
        - key: "KONG_POSTGRES_DATA_DIR"
          value: "{{ kong_postgres_data_dir }}"
        - key: "KONG_POSTGRES_LOG_DIR"
          value: "{{ kong_postgres_log_dir }}"
        - key: "KONG_DASHBOARD_PORT"
          value: "{{ kong_dashboard_port }}"
        - key: "KONG_DASHBOARD_PASSWORD"
          value: "\"{{ kong_dashboard_password }}\""

    - name: Touch postgresql.conf
      file:
        path: "{{ kong_postgres_data_dir }}/postgresql.conf"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: Update postgresql.conf
      lineinfile:
        path: "{{ kong_postgres_data_dir }}/postgresql.conf"
        regexp: "^{{ item.key }}[\\s]*="
        line: '{{ item.key }} = {{ item.value }}'
      with_items:
        - key: "listen_addresses"
          value: "'*'"
        - key: "external_pid_file"
          value: "'/var/run/postgresql/postgresql.pid'"
        - key: "log_destination"
          value: "'stderr'"
        - key: "logging_collector"
          value: "on"
        - key: "log_directory"
          value: "'/var/log/postgresql'"
        - key: "log_filename"
          value: "'postgresql.log'"
