version: '3'

services:
  kong-database:
    command: postgres -c 'config_file=/var/lib/postgresql/data/postgresql.conf'

volumes:
  kong_log:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_LOG_DIR:-/tmp/kong_log}
      o: bind
  kong_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_POSTGRES_DATA_DIR:-/tmp/kong_postgres_data}
      o: bind
  kong_postgres_log:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_POSTGRES_LOG_DIR:-/tmp/kong_postgres_log}
      o: bind
