version: '3'

services:
  kong:
    image: "${KONG_DOCKER_TAG:-kong:0.14-alpine}"
    command: kong start --run-migrations
    depends_on:
      - kong-database
    volumes:
      - kong_log:/var/log/kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PROXY_ACCESS_LOG: /var/log/kong/proxy_access.log
      KONG_PROXY_ERROR_LOG: /var/log/kong/proxy_error.log
      KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
      KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    restart: always
    pid: host
    ports:
      - "80:8000/tcp"
      - "443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
    networks:
      - kong

  kong-database:
    image: "${KONG_PG_DOCKER_TAG:-postgres:11.1-alpine}"
    command: postgres -c 'log_destination=stderr' -c 'logging_collector=on' -c 'log_directory=/var/log/postgresql' -c 'log_filename=postgresql.log'
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
      - kong_postgres_log:/var/log/postgresql
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      PGDATA: /var/lib/postgresql/data/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    networks:
      - kong

  kong-dashboard:
    image: "${KONG_DASHBOARD_DOCKER_TAG:-pgbi/kong-dashboard:v3}"
    command: start --kong-url http://kong:8001 --basic-auth ${KONG_DASHBOARD_USER:-kong}=${KONG_DASHBOARD_PASSWORD:-kong}
    restart: always
    pid: host
    ports:
      - "${KONG_DASHBOARD_PORT:-8080}:8080/tcp"
    networks:
      - kong

networks:
  kong:

volumes:
  kong_log:
  kong_postgres_data:
  kong_postgres_log:
