version: '3'

services:
  kong:
    volumes:
      - kong_log:/var/log/kong
    environment:
      KONG_PROXY_ACCESS_LOG: /var/log/kong/proxy_access.log
      KONG_PROXY_ERROR_LOG: /var/log/kong/proxy_error.log
      KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
      KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log

  kong-database:
    command: postgres -c 'config_file=/var/lib/postgresql/data/postgresql.conf' #-c 'log_statement=all'
    volumes:
      - kong_postgres_log:/var/log/postgresql

volumes:
  kong_log:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_LOG_DIR:-/data/x_kong/kong_log}
      o: bind
  kong_postgres_log:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_POSTGRES_LOG_DIR:-/data/x_kong/kong_postgres_log}
      o: bind
  kong_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${KONG_POSTGRES_DATA_DIR:-/data/x_kong/kong_postgres_data}
      o: bind
